spring:
  profiles:
    active: dev
  config:
    location: file:/C:/opt/services/properties/operation-quasar.yml
    name: operation-quasar.yml
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8080
  servlet:
    context-path: /operation-quasar/api

satellite:
  position:
    'kenobi': [-500,-200]
    'skywalker': [100,-100]
    'sato': [500,100]


